### ISSUE TITLE
On clicking "Forgot Password?" the back ground is becoming blank then the login form is disappearing.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Account-Toolkit#173] opened 2017-06-14 06:25 UTC
Scenario:
1. Clear all history and cookie of the browser. 
2. Navigate to the URL.
3. Click "Forgot Password?" 
First the back ground is becoming blank then the login form is disappearing. It is not visibly looking good.

**Comment by deepika-Gopala** [comment] 2017-08-28 10:53
This was probably because of netwaork and performance  loading issue . Cannot replicate the issue as of now. Please let us know if the same persist.

**Comment by veereshms** [comment] 2017-09-13 07:24
Can't reproduce the issue, closing the issue for now and will be re-opened if it occur again.

**Closed by veereshms** 2017-09-13 07:24 UTC
Labels: Forgot Password
