### ISSUE TITLE
In Participant, If we create new panellist and open the list, data is getting empty in some scenario (when its done for more than 3 times).

### ISSUE THREAD

**Issue by pavankumarkolla** [OnePointGlobal/OnePoint-Global-Account-Toolkit#281] opened 2017-08-08 10:05 UTC
In Participant, If we save new panellist and open the list, data is getting empty in some scenario.

**Comment by pavankumarkolla** [comment] 2017-08-08 10:08
![image](https://user-images.githubusercontent.com/26477412/29067246-8ee829a0-7c4f-11e7-9915-c992833b5da5.png)

**Comment by veereshms** [comment] 2017-08-21 11:10
Not able to reproduce the issue, closing this issue based on "Development-Fixed" status updated by development team.

**Closed by veereshms** 2017-08-21 11:10 UTC
